### ISSUE TITLE
Create page with images

### ISSUE THREAD

**Issue by joelinfo19** [ASDU0/asdu-page#1]
### ISSUE
Replicate the image in html and css
- Modify index.html 
- Modify styles.css

![image_landing_page](https://user-images.githubusercontent.com/52236148/195968245-921f721b-788a-4b61-9563-356a8b1cfe12.PNG)

### Steps to do the issue :
-  :exclamation:  IMPORTANT You need to create a new branch from develop to do the issue
-  You need to be in branch "DEVELOP" and run 
   - ```git branch name_of_your_branch```  to create a new branch
   - ```git checkout name_of_your_branch``` to change to your branch

- You need to assign yourself in the issue
![issue](https://user-images.githubusercontent.com/52236148/195969052-7e7a696e-87a8-414e-9d01-4eb3b72a1d43.PNG)

### At the end:
- You just need to push your branch
- Push your branch you need to run:
   - ```git add .``` add your changes
   - ```git commit -m "name_of_your_commit"``` tag your changes
   - ```git push -u origin name_of_your_branch``` push your branch
- Finally you need to close the issue

![close issue](https://user-images.githubusercontent.com/52236148/195968858-6a8db7f7-cf90-4613-b9ad-3ba6938b645a.PNG)

**Comment by N-Natalia** [comment]
Termine la issue, me base en las vistas de la pagina que se tiene.
